# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1650, 950)
        self.identity_frame = QtWidgets.QFrame(Form)
        self.identity_frame.setGeometry(QtCore.QRect(1240, 260, 400, 165))
        self.identity_frame.setStyleSheet("#identity_frame {\n"
"    background-color: #EEEEEE;\n"
"    border: 2px solid black;\n"
"    border-radius: 15px;\n"
"}")
        self.identity_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.identity_frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.identity_frame.setObjectName("identity_frame")
        self.identity_frame_title = QtWidgets.QLabel(self.identity_frame)
        self.identity_frame_title.setGeometry(QtCore.QRect(0, 0, 400, 35))
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.identity_frame_title.setFont(font)
        self.identity_frame_title.setStyleSheet("background-color: #D0D0D0;\n"
"border: 2px solid black;\n"
"border-top-left-radius: 15px;\n"
"border-top-right-radius: 15px;\n"
"")
        self.identity_frame_title.setTextFormat(QtCore.Qt.PlainText)
        self.identity_frame_title.setAlignment(QtCore.Qt.AlignCenter)
        self.identity_frame_title.setObjectName("identity_frame_title")
        self.name_frame = QtWidgets.QFrame(self.identity_frame)
        self.name_frame.setGeometry(QtCore.QRect(0, 40, 400, 40))
        self.name_frame.setStyleSheet("")
        self.name_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.name_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.name_frame.setObjectName("name_frame")
        self.name_title = QtWidgets.QLabel(self.name_frame)
        self.name_title.setGeometry(QtCore.QRect(10, 0, 65, 40))
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.name_title.setFont(font)
        self.name_title.setAlignment(QtCore.Qt.AlignCenter)
        self.name_title.setObjectName("name_title")
        self.name_holder = QtWidgets.QLineEdit(self.name_frame)
        self.name_holder.setGeometry(QtCore.QRect(75, 4, 315, 30))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(13)
        self.name_holder.setFont(font)
        self.name_holder.setAutoFillBackground(False)
        self.name_holder.setStyleSheet("background-color: white;\n"
"border: 2px solid gray;\n"
"border-radius: 15px;")
        self.name_holder.setAlignment(QtCore.Qt.AlignCenter)
        self.name_holder.setReadOnly(True)
        self.name_holder.setObjectName("name_holder")
        self.time_frame = QtWidgets.QFrame(self.identity_frame)
        self.time_frame.setGeometry(QtCore.QRect(0, 80, 400, 40))
        self.time_frame.setStyleSheet("")
        self.time_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.time_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.time_frame.setObjectName("time_frame")
        self.time_title = QtWidgets.QLabel(self.time_frame)
        self.time_title.setGeometry(QtCore.QRect(10, 0, 65, 40))
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.time_title.setFont(font)
        self.time_title.setAlignment(QtCore.Qt.AlignCenter)
        self.time_title.setObjectName("time_title")
        self.time_holder = QtWidgets.QLineEdit(self.time_frame)
        self.time_holder.setGeometry(QtCore.QRect(75, 5, 315, 30))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(13)
        self.time_holder.setFont(font)
        self.time_holder.setStyleSheet("background-color: white;\n"
"border: 2px solid gray;\n"
"border-radius: 15px;")
        self.time_holder.setAlignment(QtCore.Qt.AlignCenter)
        self.time_holder.setReadOnly(True)
        self.time_holder.setObjectName("time_holder")
        self.location_frame = QtWidgets.QFrame(self.identity_frame)
        self.location_frame.setGeometry(QtCore.QRect(0, 120, 400, 40))
        self.location_frame.setStyleSheet("")
        self.location_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.location_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.location_frame.setObjectName("location_frame")
        self.location_title = QtWidgets.QLabel(self.location_frame)
        self.location_title.setGeometry(QtCore.QRect(10, 0, 65, 40))
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.location_title.setFont(font)
        self.location_title.setAlignment(QtCore.Qt.AlignCenter)
        self.location_title.setObjectName("location_title")
        self.location_holder = QtWidgets.QLineEdit(self.location_frame)
        self.location_holder.setGeometry(QtCore.QRect(75, 5, 315, 30))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(13)
        self.location_holder.setFont(font)
        self.location_holder.setStyleSheet("background-color: white;\n"
"border: 2px solid gray;\n"
"border-radius: 15px;")
        self.location_holder.setAlignment(QtCore.Qt.AlignCenter)
        self.location_holder.setReadOnly(True)
        self.location_holder.setObjectName("location_holder")
        self.records_frame = QtWidgets.QFrame(Form)
        self.records_frame.setGeometry(QtCore.QRect(1240, 435, 400, 505))
        self.records_frame.setStyleSheet("#records_frame {\n"
"    background-color: #EEEEEE;\n"
"    border: 2px solid black;\n"
"    border-radius: 15px;\n"
"}")
        self.records_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.records_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.records_frame.setObjectName("records_frame")
        self.records_frame_title = QtWidgets.QLabel(self.records_frame)
        self.records_frame_title.setGeometry(QtCore.QRect(0, 0, 400, 35))
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.records_frame_title.setFont(font)
        self.records_frame_title.setStyleSheet("background-color: #D0D0D0;\n"
"border: 2px solid black;\n"
"border-top-left-radius: 15px;\n"
"border-top-right-radius: 15px;\n"
"")
        self.records_frame_title.setAlignment(QtCore.Qt.AlignCenter)
        self.records_frame_title.setObjectName("records_frame_title")
        self.records_style_frame = QtWidgets.QFrame(self.records_frame)
        self.records_style_frame.setGeometry(QtCore.QRect(10, 45, 380, 450))
        self.records_style_frame.setStyleSheet("#records_style_frame {\n"
"    background-color: white;\n"
"    border: 2px solid gray;\n"
"    border-radius: 15px;\n"
"}")
        self.records_style_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.records_style_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.records_style_frame.setObjectName("records_style_frame")
        self.records_holder = QtWidgets.QListView(self.records_style_frame)
        self.records_holder.setEnabled(True)
        self.records_holder.setGeometry(QtCore.QRect(10, 10, 360, 430))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(13)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.records_holder.setFont(font)
        self.records_holder.setAutoFillBackground(False)
        self.records_holder.setStyleSheet("background-color: white;\n"
"border: 0px;")
        self.records_holder.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.records_holder.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.records_holder.setTextElideMode(QtCore.Qt.ElideMiddle)
        self.records_holder.setMovement(QtWidgets.QListView.Static)
        self.records_holder.setFlow(QtWidgets.QListView.TopToBottom)
        self.records_holder.setProperty("isWrapping", False)
        self.records_holder.setResizeMode(QtWidgets.QListView.Fixed)
        self.records_holder.setViewMode(QtWidgets.QListView.ListMode)
        self.records_holder.setUniformItemSizes(False)
        self.records_holder.setWordWrap(True)
        self.records_holder.setObjectName("records_holder")
        self.picture_frame = QtWidgets.QFrame(Form)
        self.picture_frame.setGeometry(QtCore.QRect(1320, 10, 240, 240))
        self.picture_frame.setStyleSheet("#picture_frame {\n"
"    background-color: #EEEEEE;\n"
"    border: 2px solid black;\n"
"    border-radius: 15px;\n"
"}")
        self.picture_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.picture_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.picture_frame.setObjectName("picture_frame")
        self.picture_holder = QtWidgets.QLabel(self.picture_frame)
        self.picture_holder.setGeometry(QtCore.QRect(10, 10, 220, 220))
        self.picture_holder.setStyleSheet("background-color: white;\n"
"border: 2px solid gray;")
        self.picture_holder.setText("")
        self.picture_holder.setScaledContents(True)
        self.picture_holder.setWordWrap(True)
        self.picture_holder.setObjectName("picture_holder")
        self.camera_style_frame = QtWidgets.QFrame(Form)
        self.camera_style_frame.setGeometry(QtCore.QRect(10, 10, 1220, 930))
        self.camera_style_frame.setStyleSheet("#camera_style_frame {\n"
"    background-color: #EEEEEE;\n"
"    border: 2px solid black;\n"
"    border-radius: 15px;\n"
"}")
        self.camera_style_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.camera_style_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.camera_style_frame.setObjectName("camera_style_frame")
        self.camera_holder = QtWidgets.QLabel(self.camera_style_frame)
        self.camera_holder.setGeometry(QtCore.QRect(10, 10, 1200, 910))
        self.camera_holder.setStyleSheet("background-color: white;\n"
"border: 2px solid gray;")
        self.camera_holder.setText("")
        self.camera_holder.setScaledContents(True)
        self.camera_holder.setObjectName("camera_holder")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.identity_frame_title.setText(_translate("Form", "個人資訊"))
        self.name_title.setText(_translate("Form", "姓名："))
        self.time_title.setText(_translate("Form", "時間："))
        self.location_title.setText(_translate("Form", "地點："))
        self.records_frame_title.setText(_translate("Form", "歷史紀錄"))
